@extends('layouts.app')
@section('title',$p->name)
@section('topbar','Projeto · '.$p->name)
@section('content')
@php
$canEdit=in_array($permission,['owner','editor','reviewer','approver'],true);$canManage=in_array($permission,['owner','approver'],true);
$flowMap=$flows->mapWithKeys(fn($f)=>[(string)$f->_id=>(string)$f->name])->all();
@endphp
<div class="page-head"><div><div class="actions"><span class="badge">{{ $p->status }}</span><span class="small muted">{{ $p->code }} · {{ $permission }}</span></div><h1 style="margin-top:8px">{{ $p->name }}</h1><p>{{ $p->description ?: 'Projeto sem descrição.' }}</p></div><div class="actions"><a class="btn" href="{{ route('relations.show',$p->_id) }}">Mapa de Relações</a><a class="btn" href="{{ route('projects.export',$p->_id) }}">Exportar project.zip</a></div></div>
<div class="grid grid-5">
@foreach([['Fluxos',$analysis['flow_count']],['Cards',$analysis['node_count']],['Conexões',$analysis['edge_count']],['Vínculos',$analysis['link_count']],['Qualidade',$analysis['quality_score'].'/100']] as $m)<div class="card metric"><div class="label">{{ $m[0] }}</div><div class="value">{{ $m[1] }}</div></div>@endforeach
</div>
<div class="actions small muted" style="margin:10px 0 16px"><span>Vínculos quebrados: <strong>{{ $analysis['broken_count'] }}</strong></span><span>Ciclos: <strong>{{ $analysis['cycle_count'] }}</strong></span><span>Órfãos: <strong>{{ count($analysis['orphans']) }}</strong></span><span>Release: <strong>{{ $p->current_release ?: '—' }}</strong></span></div>

<div class="tabs" data-tabs="projectPro"><button class="active" data-tab="map">Mapa do projeto</button><button data-tab="flows">Fluxos</button><button data-tab="search">Busca global</button><button data-tab="execution">Execução entre fluxos</button><button data-tab="impact">Impacto e qualidade</button><button data-tab="releases">Releases</button><button data-tab="io">Importar/exportar</button><button data-tab="settings">Configurações</button><button data-tab="members">Participantes</button></div>

<section class="tab-panel active" data-tab-panel-group="projectPro" data-tab-panel="map">
<div class="grid grid-2"><div class="card"><h3>Dependências entre fluxos</h3><p class="small muted">{{ count($graph['links']) }} vínculo(s) de subprocessos. Use o mapa interativo para zoom, física, busca e exploração de cards.</p><a class="btn btn-primary" href="{{ route('relations.show',$p->_id) }}">Abrir mapa interativo</a></div><div class="card"><h3>Saúde estrutural</h3>@if($analysis['broken_count'])<div class="alert alert-error">Há {{ $analysis['broken_count'] }} vínculo(s) quebrado(s). Corrija antes de criar uma release.</div>@else<div class="alert alert-success">Nenhum vínculo quebrado.</div>@endif @if($analysis['cycle_count'])<div class="alert alert-error">{{ $analysis['cycle_count'] }} ciclo(s) entre fluxos.</div>@endif</div></div>
@if($graph['broken'])<div class="card" style="margin-top:14px"><h3>Vínculos quebrados</h3><div class="table-wrap"><table><thead><tr><th>Fluxo origem</th><th>Card</th><th>Destino</th><th>Problema</th></tr></thead><tbody>@foreach($graph['broken'] as $x)<tr><td>{{ $x['source_flow_name'] }}</td><td>{{ $x['source_node_label'] }}</td><td>{{ $x['target_flow_id'] }}</td><td>{{ implode(', ',$x['reasons']) }}</td></tr>@endforeach</tbody></table></div></div>@endif
</section>

<section class="tab-panel" data-tab-panel-group="projectPro" data-tab-panel="flows">
<div class="grid grid-2"><div class="card"><div class="actions" style="justify-content:space-between"><h3>Fluxos do projeto</h3>@if($canEdit)<form method="post" action="{{ route('flows.store') }}">@csrf<input type="hidden" name="project_id" value="{{ $p->_id }}"><input type="hidden" name="name" value="Novo fluxo do projeto"><button class="btn btn-primary btn-sm">Novo fluxo</button></form>@endif</div><div class="stack">@forelse($flows as $f)<div class="project-flow-row"><div><strong>{{ $f->name }}</strong><br><span class="small muted">{{ $f->project_role ?: 'subprocess' }} · {{ $f->project_group ?: 'Geral' }} · ordem {{ $f->project_order }} · v{{ $f->current_version }} · rev {{ $f->revision }}</span></div><div class="actions"><a class="btn btn-sm" href="{{ route('flows.editor',$f->_id) }}">Abrir</a>@if($canEdit)<form method="post" action="{{ route('projects.detach',[$p->_id,$f->_id]) }}" onsubmit="return confirm('Desvincular o fluxo e mantê-lo como avulso?')">@csrf @method('DELETE')<button class="btn btn-sm">Desvincular</button></form>@endif</div></div>@empty<span class="muted">Nenhum fluxo vinculado.</span>@endforelse</div></div>
<div class="card"><h3>Adicionar fluxo existente</h3><form method="post" action="{{ route('projects.assign',$p->_id) }}" class="stack">@csrf<div class="field"><label>Fluxo avulso</label><select name="flow_id" required><option value="">Selecione</option>@foreach($available as $f)<option value="{{ $f->_id }}">{{ $f->name }}</option>@endforeach</select></div><div class="form-grid"><div class="field"><label>Papel</label><select name="role"><option value="executive">Visão executiva</option><option value="operational">Visão operacional</option><option value="subprocess" selected>Fluxo auxiliar</option><option value="support">Apoio</option></select></div><div class="field"><label>Ordem</label><input type="number" name="order" value="0" min="0"></div></div><div class="field"><label>Grupo</label><input name="group" placeholder="Geral"></div><button class="btn btn-primary" @disabled(!$canEdit)>Vincular fluxo</button></form></div></div>
</section>

<section class="tab-panel" data-tab-panel-group="projectPro" data-tab-panel="search"><div class="card"><h3>Busca global no projeto</h3><div class="actions"><input id="projectSearchInput" style="flex:1;min-width:260px" placeholder="Card, fluxo, responsável, tag, raia ou ID"><button class="btn btn-primary" id="projectSearchBtn" type="button">Buscar</button></div><div id="projectSearchResults" class="stack" style="margin-top:14px"></div></div></section>

<section class="tab-panel" data-tab-panel-group="projectPro" data-tab-panel="execution"><div class="card"><h3>Execução guiada entre fluxos</h3><p class="small muted">Calcula o menor caminho pelos vínculos de subprocessos. Depois abra cada fluxo em sequência e use o Play do editor para percorrer as etapas internas.</p><div class="form-grid"><div class="field"><label>Fluxo de origem</label><select id="pathSource">@foreach($flows as $f)<option value="{{ $f->_id }}">{{ $f->name }}</option>@endforeach</select></div><div class="field"><label>Fluxo de destino</label><select id="pathTarget">@foreach($flows as $f)<option value="{{ $f->_id }}">{{ $f->name }}</option>@endforeach</select></div></div><button class="btn btn-primary" id="pathBuild" type="button">Montar rota</button><div id="pathResults" class="actions" style="margin-top:14px"></div></div></section>

<section class="tab-panel" data-tab-panel-group="projectPro" data-tab-panel="impact"><div class="card"><h3>Impacto de alterações</h3><div class="actions"><select id="impactFlow">@foreach($flows as $f)<option value="{{ $f->_id }}">{{ $f->name }}</option>@endforeach</select><button class="btn" id="impactBtn" type="button">Analisar quem depende deste fluxo</button></div><div id="impactResults" style="margin-top:12px"></div></div><div class="card" style="margin-top:14px"><h3>Qualidade consolidada</h3><div class="table-wrap"><table><thead><tr><th>Fluxo</th><th>Qualidade</th><th>Cards</th><th>Conexões</th><th>Problemas</th><th>Cards afetados</th></tr></thead><tbody>@foreach($analysis['quality_rows'] as $row)<tr><td><a href="{{ route('flows.editor',$row['flow_id']) }}"><strong>{{ $row['name'] }}</strong></a></td><td>{{ $row['quality_score'] }}/100</td><td>{{ $row['node_count'] }}</td><td>{{ $row['edge_count'] }}</td><td>{{ $row['issue_count'] }}</td><td>{{ collect($row['issue_details']??[])->pluck('Card')->unique()->join(', ') ?: 'Nenhum' }}</td></tr>@endforeach</tbody></table></div></div></section>

<section class="tab-panel" data-tab-panel-group="projectPro" data-tab-panel="releases"><div class="grid grid-2"><div class="card"><h3>Criar release consolidada</h3><form method="post" action="{{ route('projects.release',$p->_id) }}" class="stack">@csrf<div class="field"><label>Nome</label><input name="name" placeholder="Opcional"></div><div class="field"><label>Notas</label><textarea name="notes"></textarea></div><button class="btn btn-primary" @disabled(!$canManage)>Criar release</button></form></div><div class="card"><h3>Histórico</h3><div class="stack">@forelse($releases as $r)<div class="project-flow-row"><div><strong>v{{ $r->version }} · {{ $r->name }}</strong><br><span class="small muted">{{ optional($r->created_at)->format('d/m/Y H:i') }} · qualidade {{ $r->quality_score }}/100</span></div><button type="button" class="btn btn-sm" data-release-view="{{ $r->version }}">Inspecionar</button></div>@empty<span class="muted">Nenhuma release criada.</span>@endforelse</div></div></div><div id="releaseDetails" class="card" style="margin-top:14px;display:none"></div></section>

<section class="tab-panel" data-tab-panel-group="projectPro" data-tab-panel="io"><div class="grid grid-3"><div class="card"><h3>Exportar pacote</h3><p class="small muted">Inclui project.json e todos os fluxos do projeto em `flows/`.</p><a class="btn btn-primary" href="{{ route('projects.export',$p->_id) }}">Baixar project.zip</a></div><div class="card"><h3>Importar outro project.zip</h3><form method="post" enctype="multipart/form-data" action="{{ route('projects.import.bundle') }}" class="stack">@csrf<div class="field"><input type="file" name="bundle" accept=".zip" required></div><button class="btn">Importar como novo projeto</button></form></div><div class="card"><h3>Importar múltiplos JSONs</h3><form method="post" enctype="multipart/form-data" action="{{ route('projects.import.jsons') }}" class="stack">@csrf<input type="hidden" name="name" value="{{ $p->name }} importado"><input type="hidden" name="description" value="Importação criada a partir do projeto {{ $p->name }}"><div class="field"><input type="file" name="files[]" accept=".json" multiple required></div><button class="btn">Criar novo projeto</button></form></div></div></section>

<section class="tab-panel" data-tab-panel-group="projectPro" data-tab-panel="settings"><div class="card"><form method="post" action="{{ route('projects.update',$p->_id) }}" class="stack">@csrf @method('PUT')<div class="form-grid"><div class="field"><label>Nome</label><input name="name" value="{{ $p->name }}" required></div><div class="field"><label>Código</label><input name="code" value="{{ $p->code }}"></div><div class="field"><label>Status</label><select name="status">@foreach(['draft','in_review','published','archived'] as $s)<option value="{{ $s }}" @selected($p->status===$s)>{{ $s }}</option>@endforeach</select></div><div class="field"><label>Visibilidade</label><select name="visibility"><option value="private" @selected($p->visibility==='private')>Privado</option><option value="organization" @selected($p->visibility==='organization')>Organização</option></select></div></div><div class="field"><label>Descrição</label><textarea name="description">{{ $p->description }}</textarea></div><div class="field"><label>Tags</label><input name="tags" value="{{ implode(', ',(array)($p->tags??[])) }}"></div><div class="field"><label>Fluxo padrão</label><select name="default_flow_id"><option value="">Nenhum</option>@foreach($flows as $f)<option value="{{ $f->_id }}" @selected((string)$p->default_flow_id===(string)$f->_id)>{{ $f->name }}</option>@endforeach</select></div>
@foreach(['openLinkedFlowInTab'=>'Abrir subprocesso em aba interna','projectPlayback'=>'Execução guiada entre fluxos','globalSearch'=>'Busca global do projeto','requireReleaseForPublish'=>'Exigir release para publicação do projeto'] as $key=>$label)<input type="hidden" name="{{ $key }}" value="0"><label class="small"><input type="checkbox" name="{{ $key }}" value="1" @checked(data_get($p->settings,$key,true))> {{ $label }}</label>@endforeach
<button class="btn btn-primary" @disabled(!$canEdit)>Salvar projeto</button></form><div class="divider"></div><form method="post" action="{{ route('projects.destroy',$p->_id) }}" onsubmit="return confirm('Excluir projeto? Esta ação não pode ser desfeita.')" class="actions">@csrf @method('DELETE')<label class="small"><input type="checkbox" name="delete_flows" value="1"> excluir também os fluxos</label><button class="btn btn-danger" @disabled($permission!=='owner')>Excluir projeto</button></form></div></section>

<section class="tab-panel" data-tab-panel-group="projectPro" data-tab-panel="members"><div class="card"><h3>Participantes</h3><p class="small muted">O acesso do projeto é herdado pelos fluxos vinculados.</p><form method="post" action="{{ route('projects.members',$p->_id) }}">@csrf<div class="table-wrap"><table><thead><tr><th>Usuário</th><th>Nível no projeto</th></tr></thead><tbody>@foreach($users as $user) @if($user->username!==$p->owner_username) @php($existing=collect((array)$p->members)->firstWhere('username',$user->username))<tr><td><strong>{{ $user->name }}</strong><br><span class="small muted">@{{ $user->username }}</span></td><td><select name="members[{{ $user->username }}]"><option value="">Sem acesso específico</option>@foreach(['viewer','editor','reviewer','approver'] as $level)<option value="{{ $level }}" @selected(($existing['level']??'')===$level)>{{ $level }}</option>@endforeach</select></td></tr>@endif @endforeach</tbody></table></div><button class="btn btn-primary" style="margin-top:12px" @disabled(!$canManage)>Salvar participantes</button></form></div></section>
@endsection

@push('scripts')
<script>
(()=>{const csrf=document.querySelector('meta[name="csrf-token"]').content,projectId=@json((string)$p->_id),flowMap=@json($flowMap);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));async function api(url,opt={}){const r=await fetch(url,{method:opt.method||'GET',headers:{'Accept':'application/json','Content-Type':'application/json','X-CSRF-TOKEN':csrf},body:opt.body?JSON.stringify(opt.body):null});const d=await r.json();if(!r.ok)throw new Error(d.message||'Falha na operação');return d}
const search=async()=>{const term=document.getElementById('projectSearchInput').value.trim(),box=document.getElementById('projectSearchResults');if(!term){box.innerHTML='';return}box.innerHTML='<span class="muted">Buscando…</span>';try{const d=await api(`/api/projetos/${encodeURIComponent(projectId)}/buscar?q=${encodeURIComponent(term)}`);box.innerHTML=d.results.length?d.results.map(x=>`<a class="card" href="/processos/${encodeURIComponent(x.flow_id)}/editor${x.kind==='node'?`?focus_node=${encodeURIComponent(x.target_id)}`:''}"><strong>${esc(x.label)}</strong><br><span class="small muted">${esc(x.flow_name)} · ${esc(x.context)}</span></a>`).join(''):'<span class="muted">Nenhum resultado.</span>'}catch(e){box.innerHTML=`<div class="alert alert-error">${esc(e.message)}</div>`}};document.getElementById('projectSearchBtn')?.addEventListener('click',search);document.getElementById('projectSearchInput')?.addEventListener('keydown',e=>{if(e.key==='Enter')search()});
document.getElementById('pathBuild')?.addEventListener('click',async()=>{const box=document.getElementById('pathResults');try{const d=await api(`/api/projetos/${encodeURIComponent(projectId)}/caminho`,{method:'POST',body:{source:document.getElementById('pathSource').value,target:document.getElementById('pathTarget').value}});box.innerHTML=d.path.length?d.path.map((id,i)=>`<a class="btn ${i===0?'btn-primary':''}" href="/processos/${encodeURIComponent(id)}/editor">${i+1}. ${esc(flowMap[id]||id)}</a>`).join('<span>→</span>'):'<div class="alert alert-error">Não existe rota entre os fluxos selecionados.</div>'}catch(e){box.innerHTML=`<div class="alert alert-error">${esc(e.message)}</div>`}});
document.getElementById('impactBtn')?.addEventListener('click',async()=>{const id=document.getElementById('impactFlow').value,box=document.getElementById('impactResults');try{const d=await api(`/api/projetos/${encodeURIComponent(projectId)}/impacto/${encodeURIComponent(id)}`);box.innerHTML=d.impact.length?`<div class="alert alert-error">${d.impact.length} card(s) dependem deste fluxo.</div><div class="table-wrap"><table><thead><tr><th>Fluxo pai</th><th>Card</th></tr></thead><tbody>${d.impact.map(x=>`<tr><td>${esc(x.source_flow_name)}</td><td>${esc(x.source_node_label)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="alert alert-success">Nenhum outro fluxo depende diretamente dele.</div>'}catch(e){box.innerHTML=`<div class="alert alert-error">${esc(e.message)}</div>`}});
document.querySelectorAll('[data-release-view]').forEach(b=>b.addEventListener('click',async()=>{const box=document.getElementById('releaseDetails');try{const d=await api(`/api/projetos/${encodeURIComponent(projectId)}/releases/${b.dataset.releaseView}`);box.style.display='block';box.innerHTML=`<h3>Release ${esc(d.release.version)} · ${esc(d.release.name)}</h3><p>${esc(d.release.notes||'')}</p><div class="table-wrap"><table><thead><tr><th>Fluxo</th><th>Versão</th><th>Revisão</th><th>Hash</th></tr></thead><tbody>${d.flows.map(f=>`<tr><td>${esc(f.flow_name)}</td><td>${esc(f.version)}</td><td>${esc(f.revision)}</td><td><code>${esc(String(f.document_hash||'').slice(0,16))}…</code></td></tr>`).join('')}</tbody></table></div>`;box.scrollIntoView({behavior:'smooth',block:'nearest'})}catch(e){box.style.display='block';box.innerHTML=`<div class="alert alert-error">${esc(e.message)}</div>`}}))})();
</script>
@endpush
