@extends('layouts.app')
@section('title','Gestão de Acesso e Auditoria')
@section('topbar','Gestão de Acesso e Auditoria')
@section('content')
@php($active=$users->where('active',true)->count()) @php($admins=$users->where('active',true)->where('role','admin')->count())
<div class="page-head"><div><h1>Gestão de Acesso e Auditoria</h1><p>Administre a coleção compartilhável <code>users</code>, perfis, bloqueios, senhas e o histórico de ações da plataforma.</p></div></div>
<div class="grid grid-5"><div class="card metric"><div class="label">Usuários</div><div class="value">{{ $users->count() }}</div></div><div class="card metric"><div class="label">Ativos</div><div class="value">{{ $active }}</div></div><div class="card metric"><div class="label">Inativos</div><div class="value">{{ $users->count()-$active }}</div></div><div class="card metric"><div class="label">Administradores</div><div class="value">{{ $admins }}</div></div><div class="card metric"><div class="label">Eventos auditados</div><div class="value">{{ $logs->count() }}</div></div></div>
<div class="tabs" data-tabs="accessPro" style="margin-top:18px"><button class="active" data-tab="directory">Diretório</button><button data-tab="create">Novo usuário</button><button data-tab="edit">Editar acesso</button><button data-tab="delete">Excluir</button><button data-tab="audit">Auditoria</button></div>
<section class="tab-panel active" data-tab-panel-group="accessPro" data-tab-panel="directory"><div class="card"><h3>Diretório</h3><div class="form-grid"><div class="field"><label>Pesquisar</label><input id="userSearch" placeholder="Nome, login ou e-mail"></div><div class="field"><label>Perfil</label><select id="roleFilter"><option value="">Todos</option><option value="user">Usuário</option><option value="head_comercial">Head Comercial</option><option value="admin">Administrador</option></select></div><div class="field"><label>Situação</label><select id="statusFilter"><option value="">Todos</option><option value="active">Ativos</option><option value="inactive">Inativos</option></select></div></div><div class="table-wrap" style="margin-top:12px"><table id="usersDirectory"><thead><tr><th>Usuário</th><th>Nome</th><th>E-mail</th><th>Perfil</th><th>Situação</th><th>Criado</th><th>Atualizado</th></tr></thead><tbody>@foreach($users as $u)<tr data-user-search="{{ Str::lower($u->username.' '.$u->name.' '.$u->email) }}" data-role="{{ $u->role }}" data-active="{{ $u->active?'active':'inactive' }}"><td>@{{ $u->username }}</td><td>{{ $u->name }}</td><td>{{ $u->email }}</td><td>{{ $u->role }}</td><td>{{ $u->active?'Ativo':'Inativo' }}</td><td>{{ optional($u->created_at)->format('d/m/Y H:i') }}</td><td>{{ optional($u->updated_at)->format('d/m/Y H:i') }}</td></tr>@endforeach</tbody></table></div></div></section>
<section class="tab-panel" data-tab-panel-group="accessPro" data-tab-panel="create"><div class="card"><h3>Novo usuário</h3><p class="small muted">O hash permanece no campo legado <code>hashed_password</code>, compatível com a base anterior.</p><form method="post" action="{{ route('users.store') }}" class="stack">@csrf<div class="form-grid"><div class="field"><label>Usuário</label><input name="username" required></div><div class="field"><label>Nome</label><input name="name" required></div><div class="field"><label>E-mail</label><input type="email" name="email" required></div><div class="field"><label>Perfil</label><select name="role"><option value="user">Usuário</option><option value="head_comercial">Head Comercial</option><option value="admin">Administrador</option></select></div></div><div class="field"><label>Senha inicial</label><input type="password" name="password" minlength="8" required></div><button class="btn btn-primary">Criar usuário</button></form></div></section>
<section class="tab-panel" data-tab-panel-group="accessPro" data-tab-panel="edit"><div class="stack">@foreach($users as $u)<div class="card"><div class="actions" style="justify-content:space-between"><div><strong>{{ $u->name }}</strong><br><span class="small muted">@{{ $u->username }}</span></div><span class="badge">{{ $u->role }}</span></div><form method="post" action="{{ route('users.update',$u->username) }}" class="stack" style="margin-top:12px">@csrf @method('PUT')<div class="form-grid"><div class="field"><label>Nome</label><input name="name" value="{{ $u->name }}" required></div><div class="field"><label>E-mail</label><input type="email" name="email" value="{{ $u->email }}" required></div><div class="field"><label>Perfil</label><select name="role">@foreach(['user','head_comercial','admin'] as $r)<option value="{{ $r }}" @selected($u->role===$r)>{{ $r }}</option>@endforeach</select></div><div class="field"><label>Nova senha opcional</label><input type="password" minlength="8" name="password"></div></div><input type="hidden" name="active" value="0"><label class="small"><input type="checkbox" name="active" value="1" @checked($u->active)> acesso ativo</label><button class="btn btn-primary btn-sm">Salvar alterações</button></form></div>@endforeach</div></section>
<section class="tab-panel" data-tab-panel-group="accessPro" data-tab-panel="delete"><div class="card"><h3>Exclusão permanente</h3><p class="small muted">A própria conta da sessão e o último administrador ativo são protegidos.</p><div class="stack">@foreach($users as $u) @if($u->username!==auth()->user()->username)<div class="project-flow-row"><span><strong>{{ $u->name }}</strong><br><span class="small muted">@{{ $u->username }} · {{ $u->role }}</span></span><form method="post" action="{{ route('users.destroy',$u->username) }}" data-delete-user="{{ $u->username }}">@csrf @method('DELETE')<button class="btn btn-danger btn-sm">Excluir</button></form></div>@endif @endforeach</div></div></section>
<section class="tab-panel" data-tab-panel-group="accessPro" data-tab-panel="audit"><div class="card"><div class="actions" style="justify-content:space-between"><h3>Auditoria</h3><button type="button" class="btn btn-sm" id="auditCsv">Exportar CSV</button></div><div class="form-grid"><div class="field"><label>Filtrar ação</label><input id="auditAction" placeholder="Login, salvou fluxo, publicou..."></div><div class="field"><label>Responsável</label><select id="auditActor"><option value="">Todos</option>@foreach($logs->pluck('user')->filter()->unique()->sort() as $actor)<option value="{{ $actor }}">{{ $actor }}</option>@endforeach</select></div></div><div class="table-wrap" style="margin-top:12px"><table id="auditTable"><thead><tr><th>Data</th><th>Usuário</th><th>Ação</th><th>Detalhes</th></tr></thead><tbody>@foreach($logs as $log)<tr data-action="{{ Str::lower($log->action) }}" data-actor="{{ $log->user }}"><td>{{ optional($log->timestamp)->format('d/m/Y H:i:s') }}</td><td>{{ $log->user }}</td><td>{{ $log->action }}</td><td><code>{{ json_encode($log->details,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) }}</code></td></tr>@endforeach</tbody></table></div></div></section>
@endsection
@push('scripts')
<script>
(()=>{const s=document.getElementById('userSearch'),r=document.getElementById('roleFilter'),st=document.getElementById('statusFilter'),rows=[...document.querySelectorAll('#usersDirectory tbody tr')];function f(){const q=s.value.trim().toLowerCase();rows.forEach(x=>x.hidden=!!((q&&!x.dataset.userSearch.includes(q))||(r.value&&x.dataset.role!==r.value)||(st.value&&x.dataset.active!==st.value)))}[s,r,st].forEach(x=>x.addEventListener(x===s?'input':'change',f));document.querySelectorAll('[data-delete-user]').forEach(form=>form.addEventListener('submit',e=>{const u=form.dataset.deleteUser,typed=prompt(`Digite ${u} para confirmar a exclusão permanente:`);if((typed||'').trim().toLowerCase()!==u.toLowerCase())e.preventDefault()}));const aa=document.getElementById('auditAction'),ac=document.getElementById('auditActor'),ar=[...document.querySelectorAll('#auditTable tbody tr')];function af(){const q=aa.value.trim().toLowerCase();ar.forEach(x=>x.hidden=!!((q&&!x.dataset.action.includes(q))||(ac.value&&x.dataset.actor!==ac.value)))}aa.addEventListener('input',af);ac.addEventListener('change',af);document.getElementById('auditCsv').onclick=()=>{const visible=ar.filter(x=>!x.hidden),csv=['Data;Usuário;Ação;Detalhes',...visible.map(x=>[...x.cells].map(c=>'"'+c.innerText.replaceAll('"','""')+'"').join(';'))].join('\r\n'),blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='fluxos_luiz_auditoria.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}})();
</script>
@endpush
